### ISSUE TITLE
Report shows encoded HTML instead of HTML

### ISSUE THREAD

**Issue by emteknetnz** [bringyourownideas/silverstripe-maintenance#215] opened 2024-04-02 03:36 UTC
CMS 5 using 3.x-dev

![image](https://github.com/bringyourownideas/silverstripe-maintenance/assets/4809037/6e58b82e-9c90-4cd5-bf19-b6bc8b876221)

**Comment by GuySartorelli** [comment] 2024-04-30 00:18
This is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/11191

**Closed by GuySartorelli** 2024-04-30 00:18 UTC
Labels: type/bug, impact/medium, affects/v5
